FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install --quiet
RUN npm install -g nodemon

EXPOSE 3000

CMD [ "nodemon", "-L" ]
