FROM node:6.9.4

ENV NODE_MODULE_INSTALLATION_PATH /usr/src/modules
ENV NODE_PATH $NODE_MODULE_INSTALLATION_PATH/node_modules

WORKDIR $NODE_MODULE_INSTALLATION_PATH

RUN npm install dotenv@1.2.0 node-sass-middleware

WORKDIR /usr/src/app

EXPOSE 3000

CMD [ "node", "keystone.js" ]
